name: xpBuild
permissions:
  contents: read
  pull-requests: write
on:
  push:
    tags: ["xpv*"]
  pull_request:
    branches: ["xpro"]
  workflow_dispatch:
jobs:
  linux:
    permissions:
      contents: read
      pull-requests: write
      packages: write
    uses: externpro/externpro/.github/workflows/build-linux.yml@26.01.4
    secrets:
      automation_token: ${{ secrets.GHCR_TOKEN }}
    with: {}
  macos:
    uses: externpro/externpro/.github/workflows/build-macos.yml@26.01.4
    secrets: inherit
    with: {}
  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@26.01.4
    secrets: inherit
    with: {}
